base: 'https://www.teamspirit-therapie.de/'
baseVariants:
  -
    base: 'https://www.teamspirit-therapie.intern/'
    condition: 'applicationContext == "Development"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: De
    hreflang: de-DE
    direction: ltr
    flag: de
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    suffix: /
    index: ''
    map:
      /: 0
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\nAllow: /\nDisallow: /typo3/\nDisallow: /typo3conf/\nDisallow: /typo3temp/var/*\nAllow: /typo3conf/ext/\nAllow: /typo3temp/\n\nDisallow: /*/Private/*\nDisallow: /*?id=*\nDisallow: /*cHash\nDisallow: /*tx_powermail_pi1\n\nSitemap: https://www.teamspirit-therapie.de/sitemap.xml\n"
settings:
  pidStartpage: '1'
  pidMetaNavigation: '22'
websiteTitle: 'Team Spirit'
